#!/usr/bin/env python3
"""Day-2 cross-day drift analysis. THE question: does pinning collapse cross-day
verdict drift toward the within-day bar? Compares rep3 (day 2, 2026-09-03) against
rep1 (day 1, 2026-09-01) per (model × arm); the within-day bar comes from day-1's
rep1-vs-rep2 flips. Raises on a missing file rather than skipping."""
import json
from pathlib import Path

ROOT = Path(__file__).parent / "results" / "D"
AGENTS = ["crm-followup", "email-triage", "expense-categorization",
          "recap", "reply-draft", "transcript-en"]
MODELS = {"z-ai/glm-5.3": "z-ai_glm-5.3", "moonshotai/kimi-k3": "moonshotai_kimi-k3"}


def load_arm(arm_dir, msafe):
    out = {}
    for a in AGENTS:
        p = ROOT / arm_dir / f"{a}__{msafe}.json"
        d = json.loads(p.read_text())
        out[a] = {c["id"]: (c["split"], bool(c["passed"])) for c in d["cases"]}
    return out


def flips(a, b, split=None):
    f = n = 0
    for exam in a:
        for cid, (s, ok) in a[exam].items():
            if cid in b[exam] and (split is None or s == split):
                n += 1
                f += (ok != b[exam][cid][1])
    return f, n


def pooled(v, split):
    p = n = 0
    for exam in v:
        for _, (s, ok) in v[exam].items():
            if s == split:
                n += 1
                p += ok
    return p, n


def main():
    print("## Day-2 cross-day analysis (generated by analyze_day2.py)\n")
    for model, msafe in MODELS.items():
        print(f"### {model}\n")
        arms = {lbl: load_arm(lbl, msafe) for lbl in
                ["pinned_rep1", "pinned_rep2", "unpinned_rep1", "unpinned_rep2",
                 "pinned_rep3", "unpinned_rep3"]}
        for lbl in ["pinned_rep3", "unpinned_rep3"]:
            hp, hn = pooled(arms[lbl], "heldout")
            tp, tn = pooled(arms[lbl], "train")
            print(f"- {lbl} (day 2): train {tp}/{tn}, heldout {hp}/{hn}")
        wf_p, wn = flips(arms["pinned_rep1"], arms["pinned_rep2"])
        wf_u, _ = flips(arms["unpinned_rep1"], arms["unpinned_rep2"])
        cf_p, cn = flips(arms["pinned_rep1"], arms["pinned_rep3"])
        cf_u, _ = flips(arms["unpinned_rep1"], arms["unpinned_rep3"])
        print(f"- within-day bar (day-1 rep1↔rep2): pinned {wf_p}/{wn}, unpinned {wf_u}/{wn}")
        print(f"- **CROSS-DAY (day-1 rep1 ↔ day-2 rep3): pinned {cf_p}/{cn}, unpinned {cf_u}/{cn}**")
        hf_p, hn2 = flips(arms["pinned_rep1"], arms["pinned_rep3"], split="heldout")
        hf_u, _ = flips(arms["unpinned_rep1"], arms["unpinned_rep3"], split="heldout")
        print(f"- cross-day heldout-only flips: pinned {hf_p}/{hn2}, unpinned {hf_u}/{hn2}\n")


if __name__ == "__main__":
    main()
