#!/usr/bin/env python3
"""Day-1 analysis for the provider-pin probes. Pre-registered questions (DESIGN.md):
D1 same-day pooled heldout score pinned vs unpinned; D2 within-day rep1-vs-rep2 verdict
flips pinned vs unpinned. Tokens pooled from metrics_totals ONLY (CLAUDE.md gotcha 13).
Emits a markdown fragment on stdout; raises on a missing/odd file rather than skipping."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent / "results"
AGENTS = ["crm-followup", "email-triage", "expense-categorization",
          "recap", "reply-draft", "transcript-en"]
MODELS = {"z-ai/glm-5.3": "z-ai_glm-5.3", "moonshotai/kimi-k3": "moonshotai_kimi-k3"}


def load(p):
    d = json.loads(p.read_text())
    verdicts = {}
    for c in d["cases"]:
        # runner results: per-case dicts with id/split/passed
        verdicts[c["id"]] = (c["split"], bool(c["passed"]))
    mt = d["metrics_totals"]
    return verdicts, mt


def pooled(verdicts_by_exam, split):
    n = p = 0
    for v in verdicts_by_exam.values():
        for _, (s, ok) in v.items():
            if s == split:
                n += 1
                p += ok
    return p, n


def flips(a_by_exam, b_by_exam):
    f = n = 0
    for exam in a_by_exam:
        if exam not in b_by_exam:
            continue
        a, b = a_by_exam[exam], b_by_exam[exam]
        for cid in a:
            if cid in b:
                n += 1
                f += (a[cid][1] != b[cid][1])
    return f, n


def arm(arm_dir, msafe):
    out, toks, gaps = {}, {"prompt_tokens": 0, "completion_tokens": 0}, []
    for a in AGENTS:
        p = ROOT / arm_dir / f"{a}__{msafe}.json"
        if not p.exists():
            gaps.append(a)
            continue
        v, mt = load(p)
        out[a] = v
        for k in toks:
            toks[k] += int(mt.get(k, 0))
    return out, toks, gaps


def main():
    print("## Day-1 numbers (generated by analyze_day1.py)\n")
    for model, msafe in MODELS.items():
        print(f"### {model}\n")
        arms = {}
        for label in ["pinned_rep1", "pinned_rep2", "unpinned_rep1", "unpinned_rep2"]:
            arms[label] = arm(f"D/{label}", msafe)
        rows = []
        for label, (v, t, g) in arms.items():
            hp, hn = pooled(v, "heldout")
            tp, tn = pooled(v, "train")
            gap = f" (GAPS: {','.join(g)})" if g else ""
            rows.append(f"| {label} | {tp}/{tn} | {hp}/{hn} | {t['prompt_tokens']} | "
                        f"{t['completion_tokens']} |{gap}")
        print("| arm | train | heldout | prompt_toks | completion_toks |")
        print("|---|---|---|---|---|")
        print("\n".join(rows) + "\n")
        # D2: within-day flips rep1 vs rep2, per arm
        for a_label in ["pinned", "unpinned"]:
            f, n = flips(arms[f"{a_label}_rep1"][0], arms[f"{a_label}_rep2"][0])
            print(f"- **D2 {a_label}**: rep1-vs-rep2 verdict flips {f}/{n}")
        # D1: pinned vs unpinned same-rep comparisons
        for rep in ["rep1", "rep2"]:
            f, n = flips(arms[f"pinned_{rep}"][0], arms[f"unpinned_{rep}"][0])
            print(f"- **D1 {rep}**: pinned-vs-unpinned verdict deltas {f}/{n}")
        print()
    # B row
    b = ROOT / "B" / "crm-followup__glm__pin-z-ai.json"
    if b.exists():
        v, mt = load(b)
        hp = sum(ok for s, ok in v.values() if s == "heldout")
        hn = sum(1 for s, _ in v.values() if s == "heldout")
        tp = sum(ok for s, ok in v.values() if s == "train")
        tn = sum(1 for s, _ in v.values() if s == "train")
        print(f"### B — GLM×crm pinned z-ai: train {tp}/{tn}, heldout {hp}/{hn}, "
              f"tokens {mt['prompt_tokens']}/{mt['completion_tokens']}\n")
    # C rows
    print("### C — mistralai/mistral-medium-3-5 (unpinned)\n")
    print("| exam | train | heldout |")
    print("|---|---|---|")
    for a in AGENTS:
        p = ROOT / "C" / f"{a}__mistral-medium-3-5.json"
        if not p.exists():
            print(f"| {a} | GAP | GAP |")
            continue
        v, _ = load(p)
        hp = sum(ok for s, ok in v.values() if s == "heldout")
        hn = sum(1 for s, _ in v.values() if s == "heldout")
        tp = sum(ok for s, ok in v.values() if s == "train")
        tn = sum(1 for s, _ in v.values() if s == "train")
        print(f"| {a} | {tp}/{tn} | {hp}/{hn} |")


if __name__ == "__main__":
    sys.exit(main())
