#!/usr/bin/env python3
"""PURE, NO-INFERENCE re-score of pass 1's recorded outputs against the
CURRENT (pass-2) evals/transcript-en/properties.py and cases.json -- pass-2
criterion v4 clause (5). Not a `test_*.py` file (`.cline/test.sh` does not
sweep it) -- a report generator, run by hand, output pasted into
RESULTS.md's PROVISIONAL section, never auto-injected.

Inputs, read-only, never modified:
  - docs/probes/transcript-long-2026-09-06/results/
      champion-gemma4-e4b-ctx16k-pass1-snapshot-run.json  (32 cases, master 3af7c4b)
      qwen3-8b-longcall.json                              (10 cases, longcall-* only)
      kimi-k3-longcall.json                               (10 cases, longcall-* only)
  - evals/transcript-en/cases.json (CURRENT, resolved by case id)

Every case is scored against the CURRENT cases.json's `input` for that id --
never the results file's own embedded `expected` block, which predates any
commit_owner-key rename this pass's clause-3 test might have forced (none
was, see RESULTS.md / the PR body). A case id present in a results file but
absent from the current cases.json is SKIPPED and reported to stderr, never
silently scored against stale content.

Runs the REAL R.run_properties (CLAUDE.md gotcha 5: an ad-hoc probe is not a
witness for the tool) twice per case: once with the SHIPPED properties.py
(PROPS), once with check_action_owner swapped for pass 1's every-hit
reference copy (PROPS_EVERY_HIT, `pass1_check_action_owner_ref.py`) -- every
other check identical in both runs. A case whose `got` is a dead run
(qwen's `{"error": ...}` payload, no `summary` key at all) is rendered as
"dead run" and excluded from the flip count -- action_items is empty on a
dead run, so check_action_owner would trivially PASS on 0 hits either way,
which is not a meaningful comparison.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "sandbox"))
import runner as R  # noqa: E402

sys.path.insert(0, str(ROOT / "evals" / "transcript-en"))
import properties as P  # noqa: E402,F401 (import proves the shipped module loads)

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
from pass1_check_action_owner_ref import check_action_owner_every_hit  # noqa: E402

CASES_BY_ID = {
    c["id"]: c
    for c in json.loads((ROOT / "evals" / "transcript-en" / "cases.json").read_text())["cases"]
}

PROPS = R.load_properties("transcript-en")
PROPS_EVERY_HIT = [
    (name, check_action_owner_every_hit if name == "check_action_owner" else fn)
    for name, fn in PROPS
]

RESULTS_DIR = _HERE / "results"
MODEL_FILES = [
    ("gemma4-e4b-ctx16k (champion, PROPOSED)",
     RESULTS_DIR / "champion-gemma4-e4b-ctx16k-pass1-snapshot-run.json"),
    ("qwen3:8b", RESULTS_DIR / "qwen3-8b-longcall.json"),
    ("moonshotai/kimi-k3 (pinned)", RESULTS_DIR / "kimi-k3-longcall.json"),
]


def score_file(path: Path) -> list:
    data = json.loads(path.read_text())
    rows = []
    for c in data.get("cases", []):
        cid = c["id"]
        cur = CASES_BY_ID.get(cid)
        if cur is None:
            print(f"  SKIP {cid}: absent from the CURRENT cases.json", file=sys.stderr)
            continue
        got = c.get("got") or {}
        dead = not isinstance(got, dict) or ("error" in got and "summary" not in got)
        input_text = cur["input"]  # CURRENT input; never the results file's embedded one
        ok, _failures, failed = R.run_properties(PROPS, input_text, got)
        failed_names = [f["check"] for f in failed]
        ok_eh, _f_eh, failed_eh = R.run_properties(PROPS_EVERY_HIT, input_text, got)
        failed_eh_names = [f["check"] for f in failed_eh]
        owner_shipped_pass = "check_action_owner" not in failed_names
        owner_every_hit_pass = "check_action_owner" not in failed_eh_names
        flip = (not dead) and (not owner_every_hit_pass) and owner_shipped_pass
        rows.append({
            "id": cid, "split": cur["split"], "dead": dead,
            "shipped_ok": ok, "shipped_failed": failed_names,
            "owner_shipped_pass": owner_shipped_pass,
            "owner_every_hit_pass": owner_every_hit_pass,
            "flip": flip,
        })
    return rows


def render_markdown(all_rows: list) -> str:
    lines = [
        "### PROVISIONAL — pass-2 re-score of pass-1's recorded outputs "
        "(criterion clause 5, pure, no inference)",
        "",
        "Generated by `docs/probes/transcript-long-2026-09-06/"
        "rescore_pass2_provisional.py`. Applies the SHIPPED, fixed "
        "`evals/transcript-en/properties.py` (any-hit-correct "
        "`check_action_owner`, self-joining `check_withdrawn_excluded`) via "
        "the real `R.run_properties`, to pass 1's recorded `got` output "
        "(6 Sep, pre-rebase), resolved by case id into the CURRENT "
        "`evals/transcript-en/cases.json` and scored against THAT entry's "
        "`input`/`expected` — never the `expected` block embedded in the "
        "results files. Champion and hosted rows are NOT same-day with each "
        "other's re-run (CLAUDE.md gotcha 14 — a same-day comparison is "
        "pass 3's job). Pass 3's live re-run REPLACES this table.",
        "",
    ]
    total_flips = 0
    total_dead = 0
    total_shipped_fail_owner = 0
    total_scoreable = 0
    for model, rows in all_rows:
        lines.append(f"#### {model}")
        lines.append("")
        lines.append("| id | split | shipped verdict (all checks) | "
                     "check_action_owner — SHIPPED (any-hit) | "
                     "check_action_owner — pass-1 ref (every-hit) | flip? |")
        lines.append("|---|---|---|---|---|---|")
        for r in rows:
            if r["dead"]:
                owner_shipped, owner_eh, flip_s = "dead run", "dead run", "n/a (excluded)"
                verdict = "dead run"
            else:
                owner_shipped = "PASS" if r["owner_shipped_pass"] else "FAIL"
                owner_eh = "PASS" if r["owner_every_hit_pass"] else "FAIL"
                flip_s = "**YES**" if r["flip"] else "no"
                verdict = "PASS" if r["shipped_ok"] else f"FAIL (`{', '.join(r['shipped_failed'])}`)"
            lines.append(f"| `{r['id']}` | {r['split']} | {verdict} | {owner_shipped} | "
                         f"{owner_eh} | {flip_s} |")
        n_flips = sum(1 for r in rows if r["flip"])
        n_dead = sum(1 for r in rows if r["dead"])
        n_scoreable = len(rows) - n_dead
        n_shipped_fail_owner = sum(
            1 for r in rows if not r["dead"] and not r["owner_shipped_pass"])
        lines.append("")
        lines.append(f"**{model}: {n_flips} flip(s)** FAIL-to-PASS on `check_action_owner` "
                     f"solely from the any-hit-correct semantic change ({n_dead} dead "
                     f"run(s) excluded from this count); `check_action_owner` FAILS under "
                     f"the SHIPPED rule on **{n_shipped_fail_owner} of {n_scoreable}** "
                     "scoreable case(s).")
        lines.append("")
        total_flips += n_flips
        total_dead += n_dead
        total_shipped_fail_owner += n_shipped_fail_owner
        total_scoreable += n_scoreable
    lines.append(f"**Total across all 3 models: {total_flips} flip(s); "
                 f"check_action_owner fails the SHIPPED rule on "
                 f"{total_shipped_fail_owner} of {total_scoreable} scoreable "
                 f"recorded case(s) ({total_dead} dead run(s) excluded).**")
    if total_shipped_fail_owner == 0:
        lines.append("")
        lines.append("**FINDING:** `check_action_owner` fails ZERO recorded cases under "
                     "the shipped any-hit rule across all three models — the check is "
                     "fixture-proven (test_2h/2j/2k) but currently INERT on every "
                     "recorded real output. Reported as a finding, not presented as a "
                     "clean pass.")
    return "\n".join(lines)


def main() -> int:
    all_rows = []
    for model, path in MODEL_FILES:
        if not path.exists():
            print(f"MISSING results file for {model}: {path}", file=sys.stderr)
            return 1
        all_rows.append((model, score_file(path)))
    print(render_markdown(all_rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
